FROM node:20-alpine

RUN npm install -g pnpm

WORKDIR /app

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./

COPY backend/package.json ./backend/

RUN pnpm install

COPY . .

EXPOSE 5000

CMD ["pnpm", "--filter", "backend", "dev"]
