import { z } from "zod";

export interface AIOutput {
  aboutCompany: string;
  jobSummary: string;
  responsibilities: string[];
  requirements: string[];
  niceToHave: string[];
  benefits: string[];
  interviewQuestions: {
    type: "Technical" | "Behavioral" | "Scenario";
    questionText: string;
  }[];
}

const TOTAL_INTERVIEW_QUESTIONS = 15;

export const VALID_QUESTION_TYPES = [
  "Technical",
  "Behavioral",
  "Scenario",
] as const;

export const aiGenerationOutputSchema = z.object({
  aboutCompany: z
    .string()
    .trim()
    .min(10, "aboutCompany text generated by AI is too short"),

  jobSummary: z
    .string()
    .trim()
    .min(10, "jobSummary text generated by AI is too short"),

  responsibilities: z
    .array(z.string().trim())
    .min(5, "AI output must be at least 5 responsibilities"),

  requirements: z
    .array(z.string().trim())
    .min(5, "AI output must be at least 5 required skills"),

  niceToHave: z
    .array(z.string().trim())
    .min(3, "AI output must be at least 3 nice to have skills"),

  benefits: z.array(z.string().trim()),

  interviewQuestions: z
    .array(
      z.object({
        type: z.enum(VALID_QUESTION_TYPES, {
          message: "AI returned an invalid interview question type",
        }),
        questionText: z
          .string()
          .trim()
          .min(10, "AI generated interview question is too short"),
      }),
    )
    .length(
      TOTAL_INTERVIEW_QUESTIONS,
      `AI must generate ${TOTAL_INTERVIEW_QUESTIONS} questions`,
    ),
});

export type AIGenerationOutput = z.infer<typeof aiGenerationOutputSchema>;
