import type { SelectOption } from "@/types/common";

export const LOCATIONS: SelectOption[] = [
  { value: "HaNoi", label: "Hà Nội" },
  { value: "HoChiMinh", label: "TP. Hồ Chí Minh" },
  { value: "HaiPhong", label: "Hải Phòng" },
  { value: "DaNang", label: "Đà Nẵng" },
  { value: "Hue", label: "Huế" },
  { value: "CanTho", label: "Cần Thơ" },
  { value: "ThaiNguyen", label: "Thái Nguyên" },
  { value: "PhuTho", label: "Phú Thọ" },
  { value: "LaoCai", label: "Lào Cai" },
  { value: "TuyenQuang", label: "Tuyên Quang" },
  { value: "LaiChau", label: "Lai Châu" },
  { value: "DienBien", label: "Điện Biên" },
  { value: "SonLa", label: "Sơn La" },
  { value: "QuangNinh", label: "Quảng Ninh" },
  { value: "HungYen", label: "Hưng Yên" },
  { value: "NinhBinh", label: "Ninh Bình" },
  { value: "ThanhHoa", label: "Thanh Hóa" },
  { value: "NgheAn", label: "Nghệ An" },
  { value: "HaTinh", label: "Hà Tĩnh" },
  { value: "QuangBinh", label: "Quảng Bình" },
  { value: "QuangTri", label: "Quảng Trị" },
  { value: "QuangNam", label: "Quảng Nam" },
  { value: "QuangNgai", label: "Quảng Ngãi" },
  { value: "KhanhHoa", label: "Khánh Hòa" },
  { value: "GiaLai", label: "Gia Lai" },
  { value: "DakLak", label: "Đắk Lắk" },
  { value: "LamDong", label: "Lâm Đồng" },
  { value: "DongNai", label: "Đồng Nai" },
  { value: "BaRiaVungTau", label: "Bà Rịa - Vũng Tàu" },
  { value: "TayNinh", label: "Tây Ninh" },
  { value: "LongAn", label: "Long An" },
  { value: "DongThap", label: "Đồng Tháp" },
  { value: "AnGiang", label: "An Giang" },
  { value: "KienGiang", label: "Kiên Giang" },
  { value: "CaMau", label: "Cà Mau" },
];
