import type { SelectOption } from "@/types/common";

export const LOCATIONS: SelectOption[] = [
  { value: "Ha_Noi", label: "Hà Nội" },
  { value: "Ho_Chi_Minh", label: "TP. Hồ Chí Minh" },
  { value: "Hai_Phong", label: "Hải Phòng" },
  { value: "Da_Nang", label: "Đà Nẵng" },
  { value: "Hue", label: "Huế" },
  { value: "Can_Tho", label: "Cần Thơ" },
  { value: "Thai_Nguyen", label: "Thái Nguyên" },
  { value: "Phu_Tho", label: "Phú Thọ" },
  { value: "Lao_Cai", label: "Lào Cai" },
  { value: "Tuyen_Quang", label: "Tuyên Quang" },
  { value: "Lai_Chau", label: "Lai Châu" },
  { value: "Dien_Bien", label: "Điện Biên" },
  { value: "Son_La", label: "Sơn La" },
  { value: "Quang_Ninh", label: "Quảng Ninh" },
  { value: "Hung_Yen", label: "Hưng Yên" },
  { value: "Ninh_Binh", label: "Ninh Bình" },
  { value: "Thanh_Hoa", label: "Thanh Hóa" },
  { value: "Nghe_An", label: "Nghệ An" },
  { value: "Ha_Tinh", label: "Hà Tĩnh" },
  { value: "Quang_Binh", label: "Quảng Bình" },
  { value: "Quang_Tri", label: "Quảng Trị" },
  { value: "Quang_Nam", label: "Quảng Nam" },
  { value: "Quang_Ngai", label: "Quảng Ngãi" },
  { value: "Khanh_Hoa", label: "Khánh Hòa" },
  { value: "Gia_Lai", label: "Gia Lai" },
  { value: "Dak_Lak", label: "Đắk Lắk" },
  { value: "Lam_Dong", label: "Lâm Đồng" },
  { value: "Dong_Nai", label: "Đồng Nai" },
  { value: "Ba_Ria_Vung_Tau", label: "Bà Rịa - Vũng Tàu" },
  { value: "Tay_Ninh", label: "Tây Ninh" },
  { value: "Long_An", label: "Long An" },
  { value: "Dong_Thap", label: "Đồng Tháp" },
  { value: "An_Giang", label: "An Giang" },
  { value: "Kien_Giang", label: "Kiên Giang" },
  { value: "Ca_Mau", label: "Cà Mau" },
];
