import type { SelectOption } from "@/types/common";

export const LOCATION_VALUES = [
  "HaNoi",
  "HoChiMinh",
  "HaiPhong",
  "DaNang",
  "Hue",
  "CanTho",
  "ThaiNguyen",
  "PhuTho",
  "LaoCai",
  "TuyenQuang",
  "LaiChau",
  "DienBien",
  "SonLa",
  "QuangNinh",
  "HungYen",
  "NinhBinh",
  "ThanhHoa",
  "NgheAn",
  "HaTinh",
  "QuangBinh",
  "QuangTri",
  "QuangNam",
  "QuangNgai",
  "KhanhHoa",
  "GiaLai",
  "DakLak",
  "LamDong",
  "DongNai",
  "BaRiaVungTau",
  "TayNinh",
  "LongAn",
  "DongThap",
  "AnGiang",
  "KienGiang",
  "CaMau",
] as const;

export type LocationType = (typeof LOCATION_VALUES)[number];

// value - label cho ui
const LOCATION_LABEL_MAP: Record<LocationType, string> = {
  HaNoi: "Hà Nội",
  HoChiMinh: "TP. Hồ Chí Minh",
  HaiPhong: "Hải Phòng",
  DaNang: "Đà Nẵng",
  Hue: "Huế",
  CanTho: "Cần Thơ",
  ThaiNguyen: "Thái Nguyên",
  PhuTho: "Phú Thọ",
  LaoCai: "Lào Cai",
  TuyenQuang: "Tuyên Quang",
  LaiChau: "Lai Châu",
  DienBien: "Điện Biên",
  SonLa: "Sơn La",
  QuangNinh: "Quảng Ninh",
  HungYen: "Hưng Yên",
  NinhBinh: "Ninh Bình",
  ThanhHoa: "Thanh Hóa",
  NgheAn: "Nghệ An",
  HaTinh: "Hà Tĩnh",
  QuangBinh: "Quảng Bình",
  QuangTri: "Quảng Trị",
  QuangNam: "Quảng Nam",
  QuangNgai: "Quảng Ngãi",
  KhanhHoa: "Khánh Hòa",
  GiaLai: "Gia Lai",
  DakLak: "Đắk Lắk",
  LamDong: "Lâm Đồng",
  DongNai: "Đồng Nai",
  BaRiaVungTau: "Bà Rịa - Vũng Tàu",
  TayNinh: "Tây Ninh",
  LongAn: "Long An",
  DongThap: "Đồng Tháp",
  AnGiang: "An Giang",
  KienGiang: "Kiên Giang",
  CaMau: "Cà Mau",
};

export const LOCATIONS: readonly SelectOption[] = LOCATION_VALUES.map(
  (val) => ({
    value: val,
    label: LOCATION_LABEL_MAP[val],
  }),
);
