import { z } from "zod";

const NUMBER_TECHNICAL_QUESTION = 5;
const NUMBER_BEHAVIOR_QUESTION = 3;
const NUMBER_SCENARIO_QUESTION = 2;

export type InterviewQuestionType = "Technical" | "Behavioral" | "Scenario";

export interface InterviewQuestion {
  type: InterviewQuestionType;
  questionText: string;
}

export interface AIOutput {
  aboutCompany: string; // companyName + companyDescription
  jobSummary: string; // jobTitle + department + experienceLevel + employmentType + location
  responsibilities: string[]; // ai genenerate >=5
  requirements: string[]; // requiredSkills + ai generate >=5
  niceToHave: string[]; // requiredSkills + ai generate >=3
  benefits: string[]; // benifits
  interviewQuestions: InterviewQuestion[]; // 5 tech + 3 behavior + 2 scenario
}

export const aiGenerationSchema = z.object({
  aboutCompany: z
    .string()
    .trim()
    .min(10, "aboutCompany text generated by AI is too short")
    .max(1000, "aboutCompany text generated by AI is too long"),

  jobSummary: z
    .string()
    .trim()
    .min(10, "jobSummary text generated by AI is too short")
    .max(1000, "aboutCompany text generated by AI is too long"),

  responsibilities: z
    .array(z.string().trim())
    .min(5, "AI output must be at least 5 responsibilities"),

  requirements: z
    .array(z.string().trim())
    .min(5, "AI output must be at least 5 required skills"),

  niceToHave: z
    .array(z.string().trim())
    .min(3, "AI output must be at least 3 nice to have skills"),

  benefits: z.array(z.string().trim()),

  interviewQuestions: z
    .array(
      z.object({
        type: z.enum(["Technical", "Behavioral", "Scenario"]),
        questionText: z
          .string()
          .trim()
          .min(2, "The question generated by AI is too short"),
      }),
    )
    .superRefine((questions, ctx) => {
      let technicalCount = 0;
      let behavioralCount = 0;
      let scenarioCount = 0;

      for (const q of questions) {
        if (q.type === "Technical") technicalCount++;
        else if (q.type === "Behavioral") behavioralCount++;
        else if (q.type === "Scenario") scenarioCount++;
      }

      if (
        technicalCount !== NUMBER_TECHNICAL_QUESTION ||
        behavioralCount !== NUMBER_BEHAVIOR_QUESTION ||
        scenarioCount !== NUMBER_SCENARIO_QUESTION
      ) {
        ctx.addIssue({
          code: "custom",
          message: `AI violated the rule regarding the number of interview questions. The requirement was: 5 Technical, 3 Behavioral, and 2 Scenario questions. The resulting scenario was: ${technicalCount} Tech, ${behavioralCount} Behavior, ${scenarioCount} Scenario.`,
          path: [],
        });
      }
    }),
});

export type aIGenerationOutput = z.infer<typeof aiGenerationSchema>;
